name: "âœ¨ Feature request"
description: "Request for a new business feature."
labels: ["feature"]
assignees:
  - theo-brlle
body:
  - type: textarea
    attributes:
      label: "ðŸŽ¯ Summary"
      description: "A description of your feature request."
      placeholder: "A description of your feature request."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "ðŸ“ Todos"
      description: "The list of things to develop for this feature."
      placeholder: "- [ ] Todo"
    validations:
      required: false
  - type: textarea
    attributes:
      label: "ðŸ”¬ Test information"
      description: "Some information in order to test the new feature more easily."
      placeholder: "- Test information"
    validations:
      required: false
  - type: textarea
    attributes:
      label: "ðŸ”— Links"
      description: "Links to documentation or related content that can help during the development."
      placeholder: "> - [Apple Developer documentation](https://developer.apple.com/documentation/)"
    validations:
      required: false
  - type: textarea
    attributes:
      label: "ðŸŒ… Attachments"
      description: "Screenshots or any attachment related to the feature."
      placeholder: "Drag and drop anything."
    validations:
      required: false
