name: "ðŸ”¨ Technical improvement"
description: "Propose a technical improvement."
labels: ["tech"]
assignees:
  - theo-brlle
body:
  - type: textarea
    attributes:
      label: "ðŸŽ¯ Summary"
      description: "A description of the technical improvement."
      placeholder: "A description of the technical improvement."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "ðŸ“ Todos"
      description: "The list of things to develop for this technical improvement."
      placeholder: "- [ ] Todo"
    validations:
      required: false
  - type: textarea
    attributes:
      label: "ðŸ”¬ Test information"
      description: "Some information in order to test the technical improvement more easily."
      placeholder: "- Test information"
    validations:
      required: false
  - type: textarea
    attributes:
      label: "ðŸ”— Links"
      description: "Links to documentation or related content that can help during the development."
      placeholder: "> - [Apple Developer documentation](https://developer.apple.com/documentation/)"
    validations:
      required: false
  - type: textarea
    attributes:
      label: "ðŸŒ… Attachments"
      description: "Screenshots or any attachment related to the activity."
      placeholder: "Drag and drop or paste any file."
    validations:
      required: false
